name = "FerriteCon2022"
uuid = "7682c852-ca1b-4753-bfb8-330a74abed53"
authors = ["kimauth <auth@chalmers.se> and contributors"]
version = "0.1.0"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
FerriteMeshParser = "0f8c756f-80dd-4a75-85c6-b0a5ab9d4620"

[compat]
FerriteMeshParser = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
